Update .github/workflows/server-release.yml
Co-authored-by: James Brown <jbrown@svix.com>

diff --git a/.github/workflows/server-release.yml b/.github/workflows/server-release.yml
--- a/.github/workflows/server-release.yml
+++ b/.github/workflows/server-release.yml
@@ -48,6 +48,10 @@ jobs:
         run: |
           version=$(cargo metadata --format-version 1 \
             | jq -r '.packages[] | select(.name == "svix-server") | .version')
+          if ! [[ "$version" =~ ^[0-9.]+$ ]] ; then
+             echo >&2 "Invalid version $version"
+             exit 1
+          fi
           echo "version=v${version}" >> "$GITHUB_OUTPUT"
         working-directory: server
     outputs:
